### ISSUE TITLE
MSNoise 1.6 checklist

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#141]
Getting ready for MSNoise 1.6

*Remaining Work:*

Documentation
-----------------
- [x] Update documentation for CC2 implementation
- [x] Update all plots in documentation with enough data (Workshop example from Undervolc?)
- [x] Fix citations in doc #133 
- [x] Edit readme.md

Processing
------------
- [x] Finish CC2 computation, with specific cases for CC, AC and SC
- [ ] Compare my PCC implementation with @RDePlaen & Schimmel
- [x] Stretching parameters in ``default.py``  #117
- [x] Skip and error on missing components #121 

Plotting
---------
- [ ] Single pair plotting issue #118 
- [ ] More verbosity when plot fail #111 

@RDePlaen @corentin3 any help is welcome! If you do, please use the ``master`` branch to make changes, PR etc...
