### ISSUE TITLE
MSNoise 2.0 - Checklist

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#213]
### Getting ready for MSNoise 2.0

For those who have not followed the last changes: for MSNoise 2.0 I plan on:

- Changing the default outputs of _all_ steps after CC (stack, mwcs, etc) to HDF5, aka "a single dataframe h5 file per filter/movstack/comp/pair/" and no longer "single MSEED per .....", reducing dramatically the number of outputs
- Adding PSD computations, PPSD/spectrograms and PSD-SR capabilities 
- Adding simple Ballmer-style locations
- Adding support for location-codes

With some still "under heavy discussion with myself":
- (maybe) PSD to channel-ratio (see Pedersen et al 2020))
- (maybe) Adding wavelet-based dv/v
- (maybe) Beamforming from cross-correlations (Ruigrok)

*Remaining Work:*

General
---------
- [ ] Agree on the naming of the "workflows" and "command groups": CCF, DVV, PSD, QC, etc.
- [ ] 

Documentation
-----------------
_Installation_
- [ ] Rewrite Installation instructions to make them simpler (conda install)
- [ ] Rewrite Databases part, to stress all is doable on sqlite, but MySQL/MariaDB or PostgreSQL are recommended
- [ ] Write PostgresSQL documentation
- [ ] Test !new! MySQL installation with the latest version, I think the changes imposed to make PostgreSQL work will solve the legendary GROUP-BY issue

_Graphics / visuals_
- [ ] Create new visuals for the workflow(s) - including the worfklow branching model etc
- [ ] Update all plots in documentation with enough data (Workshop example from Undervolc? or full undervolc)
- [ ] Create new screenshots from the web Admin

_API-Recipes_
- [ ] Add interaction examples
- [ ] Add API calls examples
- [ ] Check all methods in API for signature & docstrings 

_Misc_
- [ ] Fix/add citations in all pages requiring it (add references to key papers if needed)
- [ ] Edit readme.md
- [ ] Important documentation needed for the location-code support!
- [ ] Decide where to host msnoise-tomo documentation (but would be good to have it here, no? at least linked)

_Review_
- [ ] will be useful for the MSNoise2.0 paper anyway: would be cool to have 1-pager intro on "what can be done with MSNoise", citing the right refs from the >100 articles using msnoise

Processing
------------
_HDF5-related_
- [ ] Check all steps are producing identical results as single-MSEED files
- [ ] Make worfklow work with the "I process the whole archive at once" scheme
- [ ] Make workflow work with the "I'm re-processing just a few jobs" scheme (requires read-update/append-write HDF5)
- [ ] API: add all the read/save HDF dataframes from all steps to the API

_Methods_
- [ ] Compare my PCC implementation with @RDePlaen & Schimmel
- [ ] Add basic Ballmer-style location method (+config bits)
- [ ] Add the "msnoise compute_dvv" step (HDF5)
- [ ] Replace _dtt_maxdt_ by _dtt_maxdtt_ =dt/t to allow small changes at large time lag

Plotting
---------
- [ ] Single pair plotting issue #118 
- [ ] rewrite plot_dvv to make use of the results of "compute_dvv" output
- [ ] More verbosity when plot fail #111 
- [ ] Add stretching plot from Jannik Kühn
- [ ] Add "plot all" mode (looping over all pairs/filters/stacks/components) - + define data structure
- [ ] Add "apparent velocity" dashed lines on the ccftime/interferogram plots
- [ ] Add new "ccf_spectrogram" plot (image version of the spectime plot)
- [ ] Clean station map plot (cartopy + leaflet only)
- [ ] Add "group by stations" plot (aka _aurelogram_)
- [ ] Add station groups for dvv plots (cf PdF "volcan", "gpentes", "cratère")

Testing
--------
- [ ] write a second set of tests to check contents
- [ ] (maybe) re-re-retry database tests on TravisCI
- [ ] (possible?) to switch to another CI infrastructure

Rules of engagement:
------------------------
- Read carefully
- If an item has no reference next to it, open a new issue with the appropriate name, and mention it here, I'll update the link next to the item, it will make things easier to follow: Discussion (and agreement if needed), Pull-request, merge
- I'll mark items done when they are solved/merged.

**Comment by ThomasLecocq** [comment]
reminder: current master documentation is build **manually** and hosted at http://msnoise.org/doc/master/

**Comment by geotavoberny** [comment]
y? terminaste o no?
