### ISSUE TITLE
MSNoise Wish List

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#54]
- [ ] Admin interface via web interface (e.g. #25)
- [ ] Instrument response removal (e.g. #16)
- [ ] Support for Inventory/StationXML/DatalessSeed
- [ ] Support for Plugins
- [ ] Preprocessing in ObsPy (e.g. #29)
- [ ] Threading Stacks (e.g. #12)

**Comment by rantanplan77** [comment]
- [ ] scenario mode for msnoise

**Comment by ThomasLecocq** [comment]
by scenario you mean "benchmark mode" ?

**Comment by rantanplan77** [comment]
Yeah, so you can test different parameters (apart from the filters).

**Comment by ThomasLecocq** [comment]
- [ ]  add ref to https://www.mail-archive.com/msnoise@mailman-as.oma.be/

**Comment by ThomasLecocq** [comment]
threading stacks is Done!
